### ISSUE TITLE
can't run in the iOS

### ISSUE THREAD

**Issue by terry8204** [igaurab/user_location_plugin#22]
can you test it in the iOS plugin?

**Comment by konishon** [comment]
@igaurab 
code magic build for iOS throws 

```
    -> Installing user_location (0.0.1)
      - Running pre install hooks
    [!] Unable to determine Swift version for the following pods:
```

**Comment by igaurab** [comment]
@terry8204 I do not own a Mac machine so can't really test it on ios devices. I am very open to PR though.

**Comment by konishon** [comment]
@igaurab 
I have codemagic setup on https://github.com/naxa-developers/iom-open-space-portal.Where I can compile for iOS

https://medium.com/flutter-community/developing-and-debugging-flutter-apps-for-ios-without-a-mac-8d362a8ec667

**Comment by igaurab** [comment]
@nishontan thanks. Will try it for sure.

**Comment by konishon** [comment]
It build on codemagic here's the build logs
https://codemagic.io/app/5e7057c82c964659341b9932/build/5e70634d6e13eb5f2e025bfd

**Comment by smasinde** [comment]
This is the error I'm getting from this... does this help you at all?


flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown while handling a gesture:
flutter: The getter 'latitude' was called on null.
flutter: Receiver: null
flutter: Tried calling: latitude
flutter:
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
flutter: #1      _MapsPluginLayerState._moveMapToCurrentLocation (package:user_location/src/user_location_layer.dart:208:33)
flutter: #2      _MapsPluginLayerState.build.<anonymous closure> (package:user_location/src/user_location_layer.dart:273:19)
flutter: #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)


UPDATE: Works in iOS, if you are getting this error, you must first set a location from the features tab. Doesn't seem iOS allows you to grab a live location from the Sim?

Coming from Android dev that got me.

**Comment by xni06** [comment]
`0.1.2` is a based on PR #34 from 4th February - can you try the latest PR #45 from  17th March using the following to see what happens? Both have been merged into master. Thanks.

```
  user_location:
    git:
      url: "https://github.com/igaurab/user_location_plugin.git"
      ref: "d7e1cbe2e01ad3de320b36570f7a3cf9624f7433"
```
