### ISSUE TITLE
Memory leak _MapsPluginLayerState line46

### ISSUE THREAD

**Issue by amokio** [igaurab/user_location_plugin#33]
```
E/flutter (20257): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (20257): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter (20257): #0      State.setState.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1205
E/flutter (20257): #1      State.setState 
package:flutter/…/widgets/framework.dart:1240
E/flutter (20257): #2      _MapsPluginLayerState.initState.<anonymous closure> 
package:user_location/src/user_location_layer.dart:46
E/flutter (20257): #3      _RootZone.runUnaryGuarded  (dart:async/zone.dart:1316:10)
E/flutter (20257): #4      _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:339:11)
E/flutter (20257): #5      _BufferingStreamSubscription._add  (dart:async/stream_impl.dart:266:7)
E/flutter (20257): #6      _SyncStreamControllerDispatch._sendData  (dart:async/stream_controller.dart:773:19)
E/flutter (20257): #7      _StreamController._add  (dart:async/stream_controller.dart:649:7)
E/flutter (20257): #8      _StreamController.add  (dart:async/stream_controller.dart:595:5)
E/flutter (20257): #9      _rootRunUnary  (dart:async/zone.dart:1138:13)
E/flutter (20257): #10     _RootZone.runUnaryGuarded  (dart:async/zone.dart:1319:7)
E/flutter (20257): #11     _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:339:11)
E/flutter (20257): #12     _DelayedData.perform  (dart:async/stream_impl.dart:594:14)
E/flutter (20257): #13     _StreamImplEvents.handleNext  (dart:async/stream_impl.dart:710:11)
E/flutter (20257): #14     _PendingEvents.schedule.<anonymous closure>  (dart:async/stream_impl.dart:670:7)
E/flutter (20257): #15     _rootRun  (dart:async/zone.dart:1122:38)
E/flutter (20257): #16     _CustomZone.run  (dart:async/zone.dart:1023:19)
E/flutter (20257): #17     _CustomZone.runGuarded  (dart:async/zone.dart:925:7)
E/flutter (20257): #18     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:965:23)
E/flutter (20257): #19     _rootRun  (dart:async/zone.dart:1126:13)
E/flutter (20257): #20     _CustomZone.run  (dart:async/zone.dart:1023:19)
E/flutter (20257): #21     _CustomZone.runGuarded  (dart:async/zone.dart:925:7)
E/flutter (20257): #22     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:965:23)
E/flutter (20257): #23     _microtaskLoop  (dart:async/schedule_microtask.dart:43:21)
E/flutter (20257): #24     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:52:5)
```

**Comment by igaurab** [comment]
Hi, could  you please explain more about this issue?
