### ISSUE TITLE
Error after hide map screen

### ISSUE THREAD

**Issue by tomaszgruzla** [igaurab/user_location_plugin#57]
```
E/flutter (32734): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: setState() called after dispose(): _MapsPluginLayerState#50975(lifecycle state: defunct, not mounted, tickers: tracking 0 tickers)
E/flutter (32734): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter (32734): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (32734): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter (32734): #0      State.setState.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1112
E/flutter (32734): #1      State.setState 
package:flutter/…/widgets/framework.dart:1147
E/flutter (32734): #2      _MapsPluginLayerState._handleCompassDirection.<anonymous closure> 
package:user_location/src/user_location_layer.dart:240
E/flutter (32734): #3      _rootRunUnary  (dart:async/zone.dart:1134:38)
E/flutter (32734): #4      _CustomZone.runUnary  (dart:async/zone.dart:1031:19)
E/flutter (32734): #5      _CustomZone.runUnaryGuarded  (dart:async/zone.dart:933:7)
E/flutter (32734): #6      _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:338:11)
E/flutter (32734): #7      _BufferingStreamSubscription._add  (dart:async/stream_impl.dart:265:7)
E/flutter (32734): #8      _SyncStreamControllerDispatch._sendData  (dart:async/stream_controller.dart:766:19)
E/flutter (32734): #9      _StreamController._add  (dart:async/stream_controller.dart:642:7)
E/flutter (32734): #10     _StreamController.add  (dart:async/stream_controller.dart:588:5)
E/flutter (32734): #11     _rootRunUnary  (dart:async/zone.dart:1134:38)
E/flutter (32734): #12     _CustomZone.runUnary  (dart:async/zone.dart:1031:19)
E/flutter (32734): #13     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:933:7)
E/flutter (32734): #14     _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:338:11)
E/flutter (32734): #15     _DelayedData.perform  (dart:async/stream_impl.dart:593:14)
E/flutter (32734): #16     _StreamImplEvents.handleNext  (dart:async/stream_impl.dart:709:11)
E/flutter (32734): #17     _PendingEvents.schedule.<anonymous closure>  (dart:async/stream_impl.dart:669:7)
E/flutter (32734): #18     _rootRun  (dart:async/zone.dart:1122:38)
E/flutter (32734): #19     _CustomZone.run  (dart:async/zone.dart:1023:19)
E/flutter (32734): #20     _CustomZone.runGuarded  (dart:async/zone.dart:925:7)
E/flutter (32734): #21     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:965:23)
E/flutter (32734): #22     _rootRun  (dart:async/zone.dart:1126:13)
E/flutter (32734): #23     _CustomZone.run  (dart:async/zone.dart:1023:19)
E/flutter (32734): #24     _CustomZone.runGuarded  (dart:async/zone.dart:925:7)
E/flutter (32734): #25     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:965:23)
E/flutter (32734): #26     _microtaskLoop  (dart:async/schedule_microtask.dart:43:21)
E/flutter (32734): #27     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:52:5)
```

**Comment by igaurab** [comment]
@tomaszgruzla 
How can I reproduce the errors?

**Comment by tomaszgruzla** [comment]
this exception throw when my MapScreenWidget with FlutterMap was disposing/closing

**Comment by tomaszgruzla** [comment]
```
void _handleCompassDirection() {
    _compassStreamSubscription =
        FlutterCompass.events.listen((double direction) {
      setState(() {
        _direction = direction;
      });
      forceMapUpdate();
    });
  }
```
this code is not working properly

**Comment by tomaszgruzla** [comment]
v 0.1.3 works properly
