### ISSUE TITLE
No material widget found on floating action button for current location

### ISSUE THREAD

**Issue by vaishnavmhetre** [igaurab/user_location_plugin#62]
**Describe the bug**
No Material Widget found on FloatingActionButton

**To Reproduce**
1. Run the app with default scaffold with plugin

**Expected behavior**
Default provided Floating action button should be visible

**Screenshots**
![Screenshot_20200523-104240](https://user-images.githubusercontent.com/14543290/82722236-76ece500-9ce2-11ea-99c8-a9ce4b91da8c.jpg)

**Smartphone (please complete the following information):**
 - Device: OnPlus7T
 - OS: Android 10

**Additional context**
```
/// **Map code used**

class DummyHolder extends StatelessWidget {
  MapController mapController = MapController();
  UserLocationOptions userLocationOptions;

  List<Marker> markers = [
    Marker(
      width: 24.0,
      height: 24.0,
      point: LatLng(51.5, -0.09),
      builder: (ctx) => Container(
        child: FlutterLogo(),
      ),
    ),
  ];

  @override
  Widget build(BuildContext context) {
    userLocationOptions = UserLocationOptions(
      context: context,
      mapController: mapController,
      markers: markers,
      showMoveToCurrentLocationFloatingActionButton: true,
    );
    return FlutterMap(
      options: MapOptions(
        center: LatLng(51.5, -0.09),
        zoom: 13.0,
        plugins: [
          UserLocationPlugin(),
        ],
      ),
      layers: [
        TileLayerOptions(
          urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
          subdomains: ['a', 'b', 'c'],
        ),
        MarkerLayerOptions(markers: markers),
        userLocationOptions,
      ],
      mapController: mapController,
    );
  }
}


/// **Debug stacktrace**

Launching lib/main.dart on HD1901 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Debug service listening on ws://127.0.0.1:45911/byZRu8pWbUU=/ws
Syncing files to device HD1901...
I/flutter (12856): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (12856): The following assertion was thrown building InkWell(gestures: [tap], clipped to BoxShape.rectangle,
I/flutter (12856): dirty, state: _InkResponseState<InkResponse>#83f44):
I/flutter (12856): No Material widget found.
I/flutter (12856): InkWell widgets require a Material widget ancestor.
I/flutter (12856): In material design, most widgets are conceptually "printed" on a sheet of material. In Flutter's
I/flutter (12856): material library, that material is represented by the Material widget. It is the Material widget
I/flutter (12856): that renders ink splashes, for instance. Because of this, many material library widgets require that
I/flutter (12856): there be a Material widget in the tree above them.
I/flutter (12856): To introduce a Material widget, you can either directly include one, or use a widget that contains
I/flutter (12856): Material itself, such as a Card, Dialog, Drawer, or Scaffold.
I/flutter (12856): The specific widget that could not find a Material ancestor was:
I/flutter (12856):   InkWell
I/flutter (12856): The ancestors of this widget were:
I/flutter (12856):   ...
I/flutter (12856):   Positioned
I/flutter (12856):   MapsPluginLayer
I/flutter (12856):   Stack
I/flutter (12856):   _PointerListener
I/flutter (12856):   Listener
I/flutter (12856):   ...
I/flutter (12856): 
I/flutter (12856): The relevant error-causing widget was:
I/flutter (12856):   InkWell
I/flutter (12856):   file:///home/stevenson/.pub-cache/hosted/pub.dartlang.org/user_location-0.1.3/lib/src/user_location_layer.dart:258:20
I/flutter (12856): 
I/flutter (12856): When the exception was thrown, this was the stack:
I/flutter (12856): #0      debugCheckHasMaterial.<anonymous closure> (package:flutter/src/material/debug.dart:28:7)
I/flutter (12856): #1      debugCheckHasMaterial (package:flutter/src/material/debug.dart:50:4)
I/flutter (12856): #2      InkResponse.debugCheckContext (package:flutter/src/material/ink_well.dart:520:12)
I/flutter (12856): #3      _InkResponseState.build (package:flutter/src/material/ink_well.dart:843:19)
I/flutter (12856): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
I/flutter (12856): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
I/flutter (12856): #6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
I/flutter (12856): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (12856): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
I/flutter (12856): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
I/flutter (12856): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
I/flutter (12856): ...     Normal element mounting (15 frames)
I/flutter (12856): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (12856): #26     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
I/flutter (12856): ...     Normal element mounting (35 frames)
I/flutter (12856): #61     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (12856): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
I/flutter (12856): #63     _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:116:18)
I/flutter (12856): #64     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2607:19)
I/flutter (12856): #65     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:96:11)
I/flutter (12856): #66     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1866:58)
I/flutter (12856): #67     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:918:15)
I/flutter (12856): #68     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1866:13)
I/flutter (12856): #69     RenderConstrainedLayoutBuilder.layoutAndBuildChild (package:flutter/src/widgets/layout_builder.dart:174:5)
I/flutter (12856): #70     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:244:5)
I/flutter (12856): #71     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (12856): #72     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (12856): #73     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (12856): #74     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (12856): #75     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (12856): #76     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (12856): #77     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (12856): #78     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (12856): #79     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (12856): #80     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (12856): #81     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (12856): #82     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (12856): #83     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (12856): #84     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (12856): #85     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (12856): #86     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (12856): #87     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3225:13)
I/flutter (12856): #88     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (12856): #89     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:700:15)
I/flutter (12856): #90     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (12856): #91     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (12856): #92     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (12856): #93     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (12856): #94     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (12856): #95     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (12856): #96     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (12856): #97     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (12856): #98     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (12856): #99     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (12856): #100    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (12856): #101    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (12856): #102    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (12856): #103    RenderView.performLayout (package:flutter/src/rendering/view.dart:167:13)
I/flutter (12856): #104    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1630:7)
I/flutter (12856): #105    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
I/flutter (12856): #106    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:402:19)
I/flutter (12856): #107    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:13)
I/flutter (12856): #108    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
I/flutter (12856): #109    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
I/flutter (12856): #110    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
I/flutter (12856): #111    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:861:7)
I/flutter (12856): (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
I/flutter (12856): 
I/flutter (12856): ════════════════════════════════════════════════════════════════════════════════════════════════════
E/SensorManager(12856): registerListenerImpl sensorName:Rotation Vector  Non-wakeup,isWakeUpSensor:false,callingApp: com.tripspal,callingPid:12856,callingUid:10252
I/flutter (12856): Another exception was thrown: No Material widget found.
I/flutter (12856): Another exception was thrown: No Material widget found.
I/chatty  (12856): uid=10252(com.tripspal) 1.ui identical 1 line
I/flutter (12856): Another exception was thrown: No Material widget found.
I/flutter (12856): Another exception was thrown: No Material widget found.
I/flutter (12856): Another exception was thrown: No Material widget found.
I/flutter (12856): Another exception was thrown: No Material widget found.

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building InkWell(gestures: [tap], clipped to BoxShape.rectangle, dirty, state: _InkResponseState<InkResponse>#83f44):
No Material widget found.

InkWell widgets require a Material widget ancestor.
In material design, most widgets are conceptually "printed" on a sheet of material. In Flutter's material library, that material is represented by the Material widget. It is the Material widget that renders ink splashes, for instance. Because of this, many material library widgets require that there be a Material widget in the tree above them.

To introduce a Material widget, you can either directly include one, or use a widget that contains Material itself, such as a Card, Dialog, Drawer, or Scaffold.

The specific widget that could not find a Material ancestor was: InkWell
  gestures: tap
  clipped to BoxShape.rectangle
  dirty
  state: _InkResponseState<InkResponse>#83f44
The ancestors of this widget were: 
  : Positioned
    right: 20.0
    bottom: 20.0
    width: 40.0
    height: 40.0
  : MapsPluginLayer
    dependencies: [_EffectiveTickerMode]
    state: _MapsPluginLayerState#87adb
  : Stack
    alignment: AlignmentDirectional.topStart
    fit: loose
    overflow: clip
    dependencies: [Directionality]
    renderObject: RenderStack#458b4
  : GestureDetector
    startBehavior: start
  : PositionedTapDetector
    state: _TapPositionDetectorState#24fb0
  : LayoutBuilder
    renderObject: _RenderLayoutBuilder#abd0b
  : FlutterMap
    dependencies: [_EffectiveTickerMode]
    state: FlutterMapState#23a72(tickers: tracking 2 tickers)
  : DummyHolder
  : MaterialApp
    state: _MaterialAppState#0515c
  : MyApp
  ...
The relevant error-causing widget was: 
  InkWell file:///home/stevenson/.pub-cache/hosted/pub.dartlang.org/user_location-0.1.3/lib/src/user_location_layer.dart:258:20
When the exception was thrown, this was the stack: 
#0      debugCheckHasMaterial.<anonymous closure> (package:flutter/src/material/debug.dart:28:7)
#1      debugCheckHasMaterial (package:flutter/src/material/debug.dart:50:4)
#2      InkResponse.debugCheckContext (package:flutter/src/material/ink_well.dart:520:12)
#3      _InkResponseState.build (package:flutter/src/material/ink_well.dart:843:19)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by igaurab** [comment]
@vaishnavmhetre are you using the latest version from pub or directly from the gituhub?

**Comment by vaishnavmhetre** [comment]
I ran _pub upgrade_ which bumped the version to 0.1.3 equal to the to the pub version tag mentioned on Github. 

pubspec.lock snap

![Screenshot from 2020-05-23 10-54-08](https://user-images.githubusercontent.com/14543290/82722373-d3043900-9ce3-11ea-8075-024346659ff3.png)

**Comment by vaishnavmhetre** [comment]
I wrapped the FlutterMap instance in Scaffold and it worked, but no idea why!! Do we always need to wrap Widget in Scaffold to be called from Material app?

**Comment by igaurab** [comment]
Yes, I was about to tell you the same, in the build method 

```
return FlutterMap(
      options: MapOptions(
        center: LatLng(51.5, -0.09),
        zoom: 13.0,
        plugins: [
          UserLocationPlugin(),
        ],
      ),
```

You have returned the FlutterMap in the build method, the Inkwell requires one of it's parent widget to be Material Widget.

**Comment by igaurab** [comment]
`Do we always need to wrap Widget in Scaffold to be called from Material app?`

The answer is no, but since most of the widgets require you to use a Material widget as their ancestor, it is a safe option to include any Material Widget as a root widget in your build method, esp when you are creating a new page
