### ISSUE TITLE
Error using on openstreetmap layer

### ISSUE THREAD

**Issue by lucabecchetti** [igaurab/user_location_plugin#63]
**Describe the bug**

════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while handling a gesture:
The getter 'latitude' was called on null.
Receiver: null
Tried calling: latitude

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _MapsPluginLayerState._moveMapToCurrentLocation (package:user_location/src/user_location_layer.dart:168:33)
#2      _MapsPluginLayerState.build.<anonymous closure> (package:user_location/src/user_location_layer.dart:222:19)
#3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
#4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#6335d
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(365.0, 779.0)
  finalLocalPosition: Offset(11.0, 26.0)
  button: 1
  sent tap down
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by services library ══════════════════════════════════════════════════════
MissingPluginException(No implementation found for method listen on channel locationStatusStream)
════════════════════════════════════════════════════════════════════════════════════════════════════

**To Reproduce**
Click on the center icon bottom right

**Desktop (please complete the following information):**
 - OS: iOS iPhone 11 Simulator

**Comment by lucabecchetti** [comment]
up

**Comment by igaurab** [comment]
The location status stream is natively written for Android Devices using Kotlin. I might think that is the reason for the issue, although I am not sure.

Could you try using an android emulator and let me know if the error persists?

**Comment by grangoni** [comment]
Same MissingPluginException(No implementation found for method listen on channel locationStatusStream) here. (both on Samsung GS10 and Android emulator

**Comment by palicka** [comment]
same here, 
samsung S7,
in my case it was thrown on startup:
```
The following MissingPluginException was thrown while activating platform stream on channel
locationStatusStream:
MissingPluginException(No implementation found for method listen on channel locationStatusStream)

When the exception was thrown, this was the stack:
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
#2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:542:29)
#3      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:528:64)
#8      _MapsPluginLayerState._handleLocationStatusChanges (package:user_location/src/user_location_layer.dart:227:44)
#9      _MapsPluginLayerState.initialize (package:user_location/src/user_location_layer.dart:102:5)
#18     MethodChannelLocation.hasPermission (package:location_platform_interface/src/method_channel_location.dart)
#27     MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart)
(elided 33 frames from dart:async and dart:async-patch)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by services library ══════════════════════════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel locationStatusStream:
MissingPluginException(No implementation found for method listen on channel locationStatusStream)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
#2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:542:29)
#3      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:528:64)
```

**Comment by sumitbhanushali** [comment]
is this issue resolved?

**Comment by igaurab** [comment]
I am afraid not.
